### ISSUE TITLE
ef_fal_port.c有BUG

### ISSUE THREAD

**Issue by z14git** [armink-rtt-pkgs/EasyFlash#1]
ef_port_read/write/erase调用fal_partition相关函数时，地址变量传递不正确。
以ef_port_read为例：
该函数的声明如下：
`EfErrCode ef_port_read(uint32_t addr, uint32_t *buf, size_t size);`
其参数addr是一个绝对地址变量。

fal_partition_read函数的声明如下：
`int fal_partition_read(const struct fal_partition *part, uint32_t addr, uint8_t *buf, size_t size)`
其参数addr是一个相对地址变量。

所以调用fal_partition_read的方式应改为这样：
`fal_partition_read(part, addr - stm32f2_onchip_flash.addr - part->offset, (uint8_t *)buf, size);`

**Comment by armink** [comment]
不用的，fal 内部会根据分区情况，自动进行偏移，partition_read 是按照分区进行读写，不用关心 Flash 层面

**Comment by z14git** [comment]
我测试的时候，如果不修改的话会提示"Partition read error! Partition address out of bound."

**Comment by armink** [comment]
你在这里的 offset 有加上 Flash 起始地址吗？

https://github.com/RT-Thread-packages/fal/blob/c642396bd4140a9f942aad9645d38f18a10e83b6/samples/porting/fal_flash_stm32f2_port.c#L124

**Comment by armink** [comment]
还有 你的 EasyFlash 的起始地址是 0 吗？

如果使用了 fal 的分区读写，这个地址就是相对 分区的了，不能再相对 Flash 

https://github.com/armink-rtt-pkgs/EasyFlash/blob/master/inc/ef_cfg.h#L116

**Comment by z14git** [comment]
> 你在这里的 offset 有加上 Flash 起始地址吗？

已经加了，我没有修改那一行。

> 还有 你的 EasyFlash 的起始地址是 0 吗？

不是0，我的PKG_EASYFLASH_START_ADDR定义为134279168

**Comment by armink** [comment]
> 如果使用了 fal 的分区读写、这个地址就是相对 分区的了，不能再相对 Flash

PKG_EASYFLASH_START_ADDR 要改为 0 ，

**Comment by z14git** [comment]
改为0后确实可以了:thumbsup:

**Comment by armink** [comment]
回顾下这个 issue ，会不会是我的 README 写的不够具体才导致的？

方便，检查、修改下 这个 移植的介绍吗？

https://github.com/armink-rtt-pkgs/EasyFlash/blob/master/ports/README.md

**Comment by z14git** [comment]
我当初用ENV工具设置easyflash的时候还没用fal的，所以`PKG_EASYFLASH_START_ADDR`才设为flash上的实际地址。后来看移植说明的时候发现用fal有现成的文件可用，于是就选择用fal了。但是`PKG_EASYFLASH_START_ADDR`没有改为0，结果就出现这种错误了。

所以，移植说明里最好提示一下用了fal/SFUD后`PKG_EASYFLASH_START_ADDR`应该怎样设置。
